// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5TzmAVvm3ap9kS_WJuxgrc_7dnifkUOI',
    appId: '1:657589006873:web:973ff45b66b496b9403088',
    messagingSenderId: '657589006873',
    projectId: 'bansos-app-c9752',
    authDomain: 'bansos-app-c9752.firebaseapp.com',
    storageBucket: 'bansos-app-c9752.firebasestorage.app',
    measurementId: 'G-8RPPFH1LCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZR3T94sq9HuwzdUvwMCXOBsG5rT906Og',
    appId: '1:657589006873:android:536ca356041d3650403088',
    messagingSenderId: '657589006873',
    projectId: 'bansos-app-c9752',
    storageBucket: 'bansos-app-c9752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSwZOz_Efr44fZmG_OauwRSZBo-3Zv4Y',
    appId: '1:657589006873:ios:d9712db59018b2d0403088',
    messagingSenderId: '657589006873',
    projectId: 'bansos-app-c9752',
    storageBucket: 'bansos-app-c9752.firebasestorage.app',
    iosBundleId: 'com.example.bansosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSSwZOz_Efr44fZmG_OauwRSZBo-3Zv4Y',
    appId: '1:657589006873:ios:d9712db59018b2d0403088',
    messagingSenderId: '657589006873',
    projectId: 'bansos-app-c9752',
    storageBucket: 'bansos-app-c9752.firebasestorage.app',
    iosBundleId: 'com.example.bansosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5TzmAVvm3ap9kS_WJuxgrc_7dnifkUOI',
    appId: '1:657589006873:web:6ac3824ec0a16fb6403088',
    messagingSenderId: '657589006873',
    projectId: 'bansos-app-c9752',
    authDomain: 'bansos-app-c9752.firebaseapp.com',
    storageBucket: 'bansos-app-c9752.firebasestorage.app',
    measurementId: 'G-B5QDC8Q8TE',
  );
}
